### ISSUE TITLE
InApp messages animation glitch on iOS

### ISSUE THREAD

**Issue by ivansnek** [Iterable/react-native-sdk#102]
### Description
<hr/>

When trying to implement [InApp messages](https://support.iterable.com/hc/en-us/articles/360045714172-In-App-Messages-with-Iterable-s-React-Native-SDK-) with the WYSIWYG editor, the animation glitches on iOS devices, we're testing with the latest library version.

- **Display type**: Using Center or Full it always tries to display it as a slide-up animation
- **Use preset animations to show and hide the message**: Set it to true it always give the issue, using false sometimes it looks good, but almost all the time the popup glitches when it appears.
- **Display a background overlay**: The issue remains using this or not.
- We don't use **custom payload** at this moment.
- We also have tried removing all the images we had in the custom popup, but we ended up with the same result

NOTE: Setting **Use preset animations to show and hide the message** as false and using **Display Type** as Full, it works like 80% percent of times, but issue remains.

### Environment

- xcode - 12.2
- build target - iOS 11

### Tested devices
- iPhone XR - OS 14.3
- iPhone XR - OS 14.4
- iPhone 12 mini - OS 14.2.1
- iPhone 7 Plus - OS 14.2

### Iterable tested versions

- **@iterable/react-native-sdk**: 1.0.15
- **@iterable/react-native-sdk**: 1.0.18
- **@iterable/react-native-sdk**: 1.0.20

### Screen Records

- iPhone 12:

https://user-images.githubusercontent.com/1279062/104505629-cf426100-55a9-11eb-9d13-5abdeb6495d7.MOV

- iPhone 7 Plus:

https://user-images.githubusercontent.com/1279062/104505646-d8333280-55a9-11eb-820b-5487f3c2bd9a.mov

### Sample popup code used
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>In-App Testing</title>
    <meta name="description" content="Test" />
    <meta name="author" content="CT Test" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no" />
    <style type="text/css">html,
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
      }
      .backdrop-wrapper {
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 0 20px;
        height: 100%;
      }
      .close {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        border: none;
        top: 0;
        width: 48px;
        height: 48px;
        right: 0;
      }
      .container {
        position: relative;
        display: flex;
        flex-direction: column;
        background-color: white;
        border-radius: 16px;
        overflow: hidden;
        text-align: center;
        color: #1f3549;
        width: 100%;
        max-width: 330px;
        min-height: 240px;
        max-height: 240px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.25);
      }
      .content {
        display: flex;
        padding: 26px 20px;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
      }
      .content h1 {
        margin: 0;
        padding: 0;
        font-weight: bold;
        line-height: 26px;
        font-size: 22px;
      }
      .content h2 {
        margin: 0;
        padding: 0;
        font-weight: normal;
        line-height: 22px;
        font-size: 16px;
      }
      .content .text {
        margin: 12px 0 0 0;
      }
      .content .text:first-child {
        margin: 0;
      }
    </style>
  </head>
  <body>
    <div class="backdrop-wrapper">
      <div class="container">
        <a class="close" href="iterable://dismiss"> X </a>
        <div class="content">
          <h1 class="text">In-App test
          </h1>
          <h2 class="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque gravida auctor tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus.
          </h2>
        </div>
      </div>
    </div>
  </body>
</html>
```

**Comment by roninopf** [comment]
Thank you for the extensive report; just to confirm, did you also test this on Android, or iOS only? This is very likely to be a problem with our iOS SDK (the native part), I'm suspecting, but it'd be good to rule out other avenues if possible.

**Comment by ivansnek** [comment]
@roninopf Yes we did test on Android devices and issue was not present, animation is smoother on those devices, so I agree is an issue with the iOS native SDK

**Comment by ivansnek** [comment]
In case anyone else facing this issue, it was related to 2 things: 

- One of the container div CSS used: `align-items: center`. Tweak with `margin` space and `height` value.
- We're using a SVG image for a closing icon. Updated to PNG.

It seems the above issues represent an issue for iOS on "@iterable/react-native-sdk": "^1.0.18".
