### ISSUE TITLE
Unable to get deep links to work

### ISSUE THREAD

**Issue by bradherman** [Iterable/react-native-sdk#103]
We have our app set up to open `appname://foo/bar` links.  We do not use Universal Linking because we don't have a web app, so there's nowhere to send those links.

When opening `appname://` links, the app opens properly, but the `urlHandler` function never gets called. 

In `AppDelegate.m`:

```
- (BOOL)application:(UIApplication *)application
        continueUserActivity:(NSUserActivity *)userActivity
        restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {

   return [IterableAPI handleUniversalLink:userActivity.webpageURL];
}
```

In app.js:

```
      config.urlHandler = (url, context) => {
        console.log("-----------------------------------")
        console.log(url)
        console.log(context)
      }
      config.customActionHandler = (action, context) => {
        console.log("===================================")
        console.log(action)
        console.log(context)
      }
      Iterable.initialize(iterableAPIKey, config)
```

Push notifications, in-app messaging, and registering user data are all working fine, but links into the app don't seem to be getting delegated to the handler.  What are we missing?

A few quick notes... The Obj-C code above was copied from the documentation, but missing a `:` between `continueUserActivity` and `(NSUserActivity)` and causing the app to not build.  After fixing that, we get a warning: `Conflicting parameter types in implementation of 'application:continueUserActivity:restorationHandler:': 'void (^ _Nonnull __strong)(NSArray<id<UIUserActivityRestoring>> * _Nullable __strong)' vs 'void (^__strong _Nonnull)(NSArray *__strong)'`

**Comment by harrydema** [comment]
I've been able to make it work but they are not working when the app is closed and opened by a deep link
