### ISSUE TITLE
createdAt date returning null on Android

### ISSUE THREAD

**Issue by lucaswhitman** [Iterable/react-native-sdk#107]
Hi, 

We're getting ready to release an update using Iterable in app messages. We're parsing the data returned by:

```
const list = await Iterable.inAppManager.getMessages();
```

And we're noticing that the `IterableInAppMessage` on Android is missing the `createdAt` date. It's showing as a null date. iOS appears to be working just fine.

referenced here:

https://github.com/Iterable/react-native-sdk/blob/master/ts/IterableInAppClasses.ts#L137

Here's our current version info:

```
"@iterable/react-native-sdk": "1.0.21"
```

Data we see:

<img width="371" alt="Screen Shot 2021-02-04 at 16 41 16" src="https://user-images.githubusercontent.com/7506979/106969290-ce63a180-6707-11eb-9292-d0657989d981.png">

**Comment by Ayyanchira** [comment]
Thank you for reporting this @lucaswhitman! I just checked as well. Its indeed giving a null 🤯
Please expect an update soon with a fix.

**Comment by lucaswhitman** [comment]
@Ayyanchira thank you so much! Looking forward to an update, and we appreciate the fast response!

**Comment by lucaswhitman** [comment]
`expiresAt` appears to be null too, pretty sure it was coming in on iOS so you may want to check that too

**Comment by Ayyanchira** [comment]
Yep. Saw that too :) 👍
