### ISSUE TITLE
Build failed: Link Iterable_React_Native_SDK (x86_64)

### ISSUE THREAD

**Issue by flochtililoch** [Iterable/react-native-sdk#112]
I'm getting this error when trying to build our iOS app:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      type metadata for Iterable_React_Native_SDK.ReactIterableAPI in ReactIterableAPI.o
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_ReactIterableAPI in ReactIterableAPI.o
  "_RCTRegisterModule", referenced from:
      _initialize_ReactIterableAPI in RNIterableAPI.o
ld: symbol(s) not found for architecture x86_64
```

Details on my setup:
- Xcode 12.4 (12D4e)
- React Native 0.63.3
- Iterable-React-Native-SDK (1.1.0-beta1)
- Iterable-iOS-SDK (6.3.0-beta2)

I tried cleaning and removing derived data, without success so far. Any help appreciated!

**Comment by roninopf** [comment]
Hi @flochtililoch, thanks for reporting! Hmm. Without being able to see more of your setup, I'm wondering if something like this will fix your problem: https://stackoverflow.com/questions/65130609/how-to-solve-undefined-symbols-for-architecture-x86-64-on-nsscanner-swift-pod

Is the project itself fully in Objective-C or is there also a Swift bridging header? We've seen similar errors related to that as well, which in that case, all you'd have to do is create an empty Swift file and Xcode will prompt you to add a bridging header file after.

**Comment by flochtililoch** [comment]
Hi @roninopf, thanks for your reply.

I tried adding a bridging header without success. I then decided to try and reproduce the issue with a stripped down RN app, to see which of our other dependencies could create the problem. We also use [HyperTrack SDK](https://github.com/hypertrack/sdk-react-native) in our app, and it appear to conflict with Iterable.

Repro case is in [this repo](https://github.com/flochtililoch/RNTestIterable):
- I started from scratch with a new RN app (0.63.3) and disabled Flipper in order to get it to build ok on iOS.
- then installed Iterable RN SDK - iOS still builds ok
- then installed HyperTrack RN SDK - iOS fails to build with same error in the issue description:

<img width="689" alt="Screen Shot 2021-02-24 at 5 08 07 PM" src="https://user-images.githubusercontent.com/309515/109088531-6da30580-76c4-11eb-9e69-3e83b61d8881.png">

Would you have a chance to take another look?

**Comment by roninopf** [comment]
@flochtililoch I'll try to get to it ASAP! Thanks for the steps.

Have you also tried the fix mentioned here as well? https://github.com/Iterable/react-native-sdk/issues/86#issuecomment-744829518

I'm not sure it'll help since you're trying to even just build and not archive yet, but our past experience makes me think that there is definitely some kind of collision between search paths or target inclusion going on.

**Comment by flochtililoch** [comment]
The root issue of this compilation error appears the same as described in https://github.com/itinance/react-native-fs/issues/964
I tried locally to amend the `Iterable-React-Native.podspec` to use `React-Core` instead of `React`, then ran `pod install` again and compiler is happy now.

**Comment by roninopf** [comment]
@flochtililoch Interesting, thanks for the solve! Sounds like another thing to add to the RN SDK documentation list.
