### ISSUE TITLE
IOS project is crashing after adding of Iterable SDK

### ISSUE THREAD

**Issue by Luckygirlllll** [Iterable/react-native-sdk#118]
IOS project is crashing after adding of Iterable React Native SDK I'm using React Native version 0.63.4, while Iterable React Native SDK is using 0.62.2, so in order to be able to install SDK I used --legacy-peer-deps command during installation process. 

Error which I'm getting from Xcode is:

ld: warning: Could not find or use auto-linked library 'swiftWebKit'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_Iterable_React_Native_SDK in libIterable-React-Native-SDK.a(ReactIterableAPI.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_Iterable_React_Native_SDK in libIterable-React-Native-SDK.a(Serialization.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_IterableSDK in libIterable-iOS-SDK.a(CommerceItem.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_IterableSDK in libIterable-iOS-SDK.a(IterableLogging.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_IterableSDK in libIterable-iOS-SDK.a(IterableActionContext.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_IterableSDK in libIterable-iOS-SDK.a(IterableAPI.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_IterableSDK in libIterable-iOS-SDK.a(IterableAppIntegration.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_IterableSDK, __swift_FORCE_LOAD_$_swiftWebKit_$_Iterable_React_Native_SDK )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not find or use auto-linked library 'swiftWebKit'
Undefined symbol: __swift_FORCE_LOAD_$_swiftWebKit

<img width="973" alt="Screenshot 2021-03-25 at 13 00 13" src="https://user-images.githubusercontent.com/10096433/112471523-4e9f9e00-8d6c-11eb-93b6-4efdc52d2a91.png">

**Comment by roninopf** [comment]
Without seeing the project's setup at the moment, have you created a blank Swift file and bridging header?

**Comment by Luckygirlllll** [comment]
yes

**Comment by roninopf** [comment]
@Luckygirlllll Is this issue still happening? And if it is, can you group it with your current CSM ticket? It'll be much easier and faster for us to respond that way.

**Comment by Luckygirlllll** [comment]
This was a bug in the previous SDK version.
