### ISSUE TITLE
 Error: Use of undeclared identifier 'IterableAPI'

### ISSUE THREAD

**Issue by Luckygirlllll** [Iterable/react-native-sdk#119]
I was following Iterable Documentation for adding Iterable SDK for IOS and it's very confusing and unclear. 
For example, this step:  In you app register device token with Iterable.

<img width="771" alt="Screenshot 2021-03-26 at 11 22 58" src="https://user-images.githubusercontent.com/10096433/112617807-bebe2a80-8e25-11eb-9dbb-f5ab8d44a426.png">

When I go to this step I see: 
<img width="844" alt="Screenshot 2021-03-26 at 11 26 01" src="https://user-images.githubusercontent.com/10096433/112618103-18265980-8e26-11eb-830b-f72ef56438d5.png">

I'm adding this code to AppDelegate.m 

And then I see this error immediately:

<img width="803" alt="Screenshot 2021-03-26 at 11 26 55" src="https://user-images.githubusercontent.com/10096433/112618351-4e63d900-8e26-11eb-8847-845d075d48bc.png">

From where this IterableAPI should be imported?  How to fix this error?

**Comment by Luckygirlllll** [comment]
@roninopf What is the solution for this error?

**Comment by roninopf** [comment]
@Luckygirlllll Hmm, I'm wondering if it's missing without `pod install` having been run? Or perhaps a Swift file and the bridging header needs to be created? I've seen that you ran into that in one of the other issue reports.

**Comment by Luckygirlllll** [comment]
@roninopf Yeah, I added Swift file, however, there is still an error during the Archive process.
<img width="956" alt="Screenshot 2021-04-01 at 12 01 27" src="https://user-images.githubusercontent.com/10096433/113278646-7948a400-92e2-11eb-9d21-bd0252daaf85.png">

**Comment by roninopf** [comment]
@Luckygirlllll Try this fix here: https://github.com/Iterable/react-native-sdk/issues/86#issuecomment-744829518

It definitely looks like it falls under that case. If you also have a notification service extension target, you just have to follow the same steps (including making a Swift file and bridging header) for it as well.

**Comment by Luckygirlllll** [comment]
This solution helped, this error during archive is not appearing any more.
