### ISSUE TITLE
when using inAppHandler method -> type NSMutableDictionary cannot be converted to NSNumber (iOS)

### ISSUE THREAD

**Issue by natesuperdraft** [Iterable/react-native-sdk#121]
constructor(props) {
    super(props);
    this.inAppHandler = (message) => message;

    const config = new IterableConfig();
    config.autoPushRegistration = false;
    config.checkForDeferredDeepLink = true;
    config.inAppDisplayInterval = 3.0; // Min gap between in-apps. No need to set this in production.
    config.urlHandler = this.urlHandler;
    config.inAppHandler = this.inAppHandler;
    Iterable.initialize(apiKey, config); 
  }

JSON value '{
    createdAt =     {
    };
    customPayload =     {
        event = screen;
        eventName = Home;
    };
    expiresAt =     {
    };
    messageId = R7DpzM5vRfQukvkXIwu4uAJRDNnUVnGsdlPvKno5;
    read = 0;
    saveToInbox = 0;
    trigger =     {
        type = 0;
    };
}' of type NSMutableDictionary cannot be converted to NSNumber

+[RCTConvert NSNumber:]
    RCTConvert.m:57
__41-[RCTModuleMethod processMethodSignature]_block_invoke_16
__41-[RCTModuleMethod processMethodSignature]_block_invoke.164
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

**Comment by roninopf** [comment]
@natesuperdraft Thanks for the report; can we get a little more context on what you were trying to do, specifically?

**Comment by ken-brown** [comment]
Closed due to no response from user.
