### ISSUE TITLE
Error: Use of undeclared identifier 'deviceToken'

### ISSUE THREAD

**Issue by Luckygirlllll** [Iterable/react-native-sdk#123]
I'm following[ React Native Iterable documentation ](https://support.iterable.com/hc/en-us/articles/360045714132)and it says that  `didRegisterForRemoteNotificationsWithDeviceToken `should be implemented. 

<img width="727" alt="Screenshot 2021-04-02 at 12 28 20" src="https://user-images.githubusercontent.com/10096433/113408071-f2153200-93ae-11eb-9581-eaddbe6e4f10.png">

I'm adding this code to AppDelegate.m  and I'm getting an error: "Use of undeclared identifier 'deviceToken'". 

<img width="1057" alt="Screenshot 2021-04-02 at 12 27 30" src="https://user-images.githubusercontent.com/10096433/113408025-d578fa00-93ae-11eb-818d-af504cf1873b.png">

Or If I type it like this, I'm getting this error: 

<img width="1419" alt="Screenshot 2021-04-02 at 12 36 40" src="https://user-images.githubusercontent.com/10096433/113408923-8a5fe680-93b0-11eb-8b7b-daba7a3bee44.png">

**Comment by Luckygirlllll** [comment]
@roninopf What is the solution for this problem?

**Comment by roninopf** [comment]
I see that you've opened a ticket with our CSM, so I'll continue to correspond there. It'll be faster and easier to do so.

**Comment by Luckygirlllll** [comment]
@roninopf what do you mean you will correspond via CMS? I will receive messages on email about this CMS ticket from support? I can't see the statuses or progress of Iterbale CMS tickets.
