### ISSUE TITLE
XCode 12 Archive Fails

### ISSUE THREAD

**Issue by jehartzog** [Iterable/react-native-sdk#129]
![image](https://user-images.githubusercontent.com/14143246/114920442-ab7bfa80-9de6-11eb-872e-68e6c63fc78a.png)

Related issues #86 #119.

Since this is blocking us, we're going to open a CSM ticket in parallel to reporting here.

## Reproduction

1. With fresh app, follow Iterable docs to setup library

### Expected

1. Dev builds work, archive works

### Actual

1. Dev build works, archive fails with `Use of undeclared identifier 'IterableAPI'`.

## Troubleshooting steps taken

- [x]  Have `@import IterableSDK;` at the top of `AppDelegate.m` 
- [x] Added blank swift bridging header
- [x] Play with different `Library Search Paths` per [this comment](https://github.com/Iterable/react-native-sdk/issues/86#issuecomment-744829518)
- [x] Set `Always Embed Swift Standard Libraries` to `no`

## Env

1. App boilerplate created with [ignite cli v6.5](https://github.com/infinitered/ignite)
2. XCode `v12.4`
3. React Native `0.64`
4. Cocoapods `1.10.1`

**Comment by jehartzog** [comment]
At Michael's (CSM) request, here is our [AppDelegate.m](https://gist.github.com/jehartzog/e363c7f55c2f4fe82bb7f757237ae549).

**Comment by jehartzog** [comment]
We finally figured this out. There were two issues going on:

1. The original error posted here was due to my error, you can see in the listed `AppDelegate.m` that I had inadvertently nested [`@import IterableSDK;`](https://gist.github.com/jehartzog/e363c7f55c2f4fe82bb7f757237ae549#file-appdelegate-m-L12-L22) inside the flipper `#ifdef` statement. This was quickly identified by Iterable CSM for corrected.

2. We hit new errors exactly as listed in #86. For whatever reason, the setting that required config to edit was not in our application target, but in our project configuration. Once we realized the documentation was leading us to look at the incorrect place, we were finally able to archive the build. Attaching screenshot since it's XCode.

![image](https://user-images.githubusercontent.com/14143246/116119312-8788a680-a67b-11eb-821c-ff3f9ab5ff8c.png)

**Comment by 1280103995** [comment]
Hi jehartzog,
The troubleshooting steps are complete, but it not work for me.

I added ```"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"``` and ```"$(inherited)"``` to ```Library Search Paths```, but it didn’t work. (It’s worth noting that it was originally empty here)

**Comment by jehartzog** [comment]
@1280103995 I don't have much for you. After removing the `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)` entry, we actually had to add it back when we added the iterable message extension to enable rich iOS pushes. Already spent way too much time trying to configure `swift-5.0` vs not, and still not sure exactly where we ended up.

**Comment by 1280103995** [comment]
I read the first point carefully and after adjusting the import position, it worked. Cheers!
