### ISSUE TITLE
How to configure the Android side? Help me, please

### ISSUE THREAD

**Issue by 1280103995** [Iterable/react-native-sdk#141]
Now it works well on iOS, but it doesn't work at all on Android.

I have completed it according to the configuration document on the Android side:
1、add ```classpath 'com.google.gms:google-services:4.3.3'```
2、add ```apply plugin: 'com.google.gms.google-services'```
3、add ```implementation "com.google.firebase:firebase-messaging:20.2.3"```
4、add ```google-services.json``` file in app module.
5、Created an Android application on Iterable and configured Firebase Server Key. 
6、Call ```setEmail``` method and found the token in ```Audience > Contact Lookup``` devices array.

When I use ```Test Push``` to send notifications on Iterable, I can't receive them.

Am I missing any configuration? who can help me? Thank you everyone!

**Comment by chuan520** [comment]
Hey, I also encounter the same problem with you. 
I think your setup for android is correct.
Windering there push function is broken.

This is my issue link:
https://github.com/Iterable/react-native-sdk/issues/142#issue-915725523

**Comment by 1280103995** [comment]
This library conflicts with ```react-native-push-notification```, remove these codes in```AndroidManifest.xml```
```
<service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
</service>
```

**Comment by chuan520** [comment]
> This library conflicts with `react-native-push-notification`, remove these codes in`AndroidManifest.xml`
> 
> ```
> <service
>             android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
>             android:exported="false" >
>             <intent-filter>
>                 <action android:name="com.google.firebase.MESSAGING_EVENT" />
>             </intent-filter>
> </service>
> ```

Hi,
Is the Iterable react-native SDK's push notification work on your side?
cause I still can't get this work, would you mind giving me some examples about the push notification?

Also, I've checked that I don't have the code you mention in my AndroidManifest.xml.

**Comment by 1280103995** [comment]
Yes, remote push works, but in-app messages do not. Maybe you should copy some of the Iterable SDK configuration to the newly created project and try it.

**Comment by 1280103995** [comment]
Hey, it decided not to work today.

**Comment by trungls1706** [comment]
i have same problem 
cannot push noti test in android

**Comment by StephenAchieve** [comment]
Same here now
