### ISSUE TITLE
[Android] opening app via push notifications after hard-quit un-registers device

### ISSUE THREAD

**Issue by alex-a-pereira** [Iterable/react-native-sdk#147]
We're seeing an issue where opening our app via a push notification after user hard-quits (cancels) the app causes subsequent push notifications to not be received by the device. If the app was previously running (i.e. the user **didn't** hard quit the app), push notifications are received and can open the app just fine.

In our app, we use react-native-splash-screens. What's more relevant is that in order to get splash screens to show up when the app is launched, we have need to have two Activities  - MainActivity (functions as you'd expect) and SplashActivity (handles showing splash screens immediately then launches MainActivity). It appears like the issue happens only when SplashActivity is started by pressing a push notification.

---

**Repro steps:**
1. hard-quit (cancel) the app so that it's no longer running in background
2. send a push notification from iterable (action is to just open the app)
3. on device, click the push notification to open the app
4. attempt to send another push notification from iterable web UI

**Observed result:**
Step 4 fails because "user does not have required device fields" - looking into the user profile, their device has `notificationsEnabled: true` but `endpointEnabled: false` set.

Expected Result
Sending the 2nd push notification in step will properly deliver a notification.

-----
adb logcat shows that iterable attempts to make the following 4 API requests in this order whenever the app is opened after a hard-quit (i.e. when the splash screen is shown):
```
/users/disableDevice (200 resp)
/users/registerDeviceToken (200 resp)
/users/disableDevice (200 resp)
/users/registerDeviceToken (200 resp)
```

What's interesting is that those 4 API request are made regardless of what's causing the app to open after hard-quit, whether it's "launch via opening app on home screen" or "launch via press push notification." The only difference I see is that the iterable SDK will make an additional API call **before** those 4 I listed
```
/events/trackPushOpen (200 resp)
/users/disableDevice (200 resp)
/users/registerDeviceToken (200 resp)
/users/disableDevice (200 resp)
/users/registerDeviceToken (200 resp)
```

--------
relevent portion of AndroidManifest.xml
```
<activity
          android:name=".SplashActivity"
          android:theme="@style/SplashTheme"
          android:label="@string/app_name">
          <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
      </activity>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:screenOrientation="portrait"
        android:launchMode="singleTop"
        android:windowSoftInputMode="adjustPan"
        android:exported="true">
        <intent-filter>
              <!-- needed because iterable, to open the app, calls getLaunchIntentForPackage() which looks for this -->
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.INFO" />
          </intent-filter>
      </activity>
```

------

**Comment by alex-a-pereira** [comment]
looking further into this... it looks like potentially the issue is with auto push registration?? When I follow these steps this is what happens:
- hard-quit the app
- send push notification from iterable web UI
- open push notification (splash screen shows)
    - *** can't send another push notification here
- soft-close the app (press home button)
- re-open the app
    - *** logs show up TAG="IterableApi" message= "Performing automatic push registration"
- i can now send myself push notifications again

**Comment by Ayyanchira** [comment]
Hi @alex-a-pereira ,
Thanks for writing in. disableDevice and registerDeviceToken are performed when the user is already logged in and a new email or userId is set. OR if it is set to null.
When is the email being set? Does it appear that you are setting email or userId to null or new value during app launch? 
Also, which RN SDK version are you using?

**Comment by alex-a-pereira** [comment]
@Ayyanchira thanks for the quick reply!

It looks like my issue was that I was calling `setEmail` AND `setUserId` from my code - hence why I was getting 4 requests. 2 are expected (first user.email is null, then it is an actual email address). Since I've removed the `setUserId()` and am now only calling `setEmail()`, things are working as expected!

So if I'm correct it appears that forcing the autoPushRegistration process twice was causing the issue
