### ISSUE TITLE
iOS Deployment Target needs updating

### ISSUE THREAD

**Issue by hytea** [Iterable/react-native-sdk#307]
I am getting an error when trying to build my app for iOS on the latest react native SDK version the React Native SDK has an iOS deployment target of 9.0 but the Iterable iOS SDK has an iOS deployment target of 10.0. 

If I update the deployment target manually it works but it gets reset anytime I deepclean the project.

**Comment by ivansnek** [comment]
> I am getting an error when trying to build my app for iOS on the latest react native SDK version the React Native SDK has an iOS deployment target of 9.0 but the Iterable iOS SDK has an iOS deployment target of 10.0.
> 
> If I update the deployment target manually it works but it gets reset anytime I deepclean the project.

Having the same issue here! 🤚🏽 

@hytea how did you manually change this? does it work for release?

**Comment by roninopf** [comment]
Hi! Sorry we missed this, it's since been fixed in version 1.2.1. If there's a new issue with that, please feel free to open a new ticket!
