### ISSUE TITLE
Inconsistent getLastPushPayload behavior across iOS & Android

### ISSUE THREAD

**Issue by willcaul** [Iterable/react-native-sdk#342]
The [`getLastPushPayload()`](https://github.com/Iterable/react-native-sdk/blob/93bf1d42ce01fcd4c872342db3c371c2c8df7ead/ts/Iterable.ts#L283-L286) function's behavior is not consistent across platforms.

On Android, `getLastPushPayload()` only returns data corresponding to the current app session because it [stores data in memory](https://github.com/Iterable/iterable-android-sdk/blob/4c92a3c09800010fb02fc55a1ca6a66d16b6766b/iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java#L108-L110) which gets forgotten when the app is killed. 

On iOS, `getLastPushPayload()` returns data corresponding to the current app session _or a previous app session_ because it [persists data for an hour](https://github.com/Iterable/swift-sdk/blob/5f061a9335a0e18be89ec0431bbb541619aa7874/swift-sdk/Internal/InternalIterableAPI.swift#L514-L517).

In my opinion, the Android behavior is preferable. Is there a reason why the iOS behavior exists? Ideally we'd like a way to determine which payload was responsible for launching the app without running into the situation where the returned data was for a previous app launch. At the very least it would be nice to have a flag on the returned result to indicate if it was an old result or not so we can distinguish between the 2 iOS scenarios.

**Comment by mostafabrazi** [comment]
Same issue here, we keep getting last push payload even if i close the app and re-open it in iOS.

**Comment by willcaul** [comment]
I know it's been a while, but are there any updates on this issue?

**Comment by jena-chakour** [comment]
Hey @willcaul, thanks for following up. Our team is looking into this, so we will add any relevant updates here

**Comment by evantk91** [comment]
Hey @willcaul thanks for your patience. This has already been addressed as of version 6.4.13. The push payload is stored in memory and will not persist to the next app session.
