### ISSUE TITLE
In app Message and Push Notification

### ISSUE THREAD

**Issue by jmejiamu** [Iterable/react-native-sdk#346]
I am not receiving in-app message on Android and iOS. There is not custom configuration. All has been handled by default Iterable React Native SDK in-app message behavior. 

* iOS - On Iterable, the devices array is not present in user profile  when registering a new user. 
* iOS -  Does not receive Push Notification nor in-app Message

* Android -  On Iterable, the devices array is present in user profile  when registering a new user. 
* Received Push Notification, but It does not receive the in-app message.

Android's in-app messages logs
```
I/ReactNativeJS: 'not', { sentTime: 1651448351373,
      data: 
       { notificationType: 'InAppUpdate',
         itbl: '{"isGhostPush":true,"messageId":"BACKGROUND_NOTIFICATION","templateId":0}' },
      messageId: '0:1651448351386344%1e935ec0f9fd7ecd',
      ttl: 2419200,
      from: '734978458139' }
V/IterableRequest:  💛 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    Response from : https://api.iterable.com/api/inApp/getMessages
V/IterableRequest:  💛 {
      "inAppMessages": []
    }
```

* Versions
` "@iterable/react-native-sdk": "^1.2.3"`
`"react-native": "0.66.3"`

**Comment by alex-a-pereira** [comment]
Are you on iOS simulator? IIRC this behavior is consistent with my experience on iOS simulator.
Iterable can't capture the device token (iOS simulator doesn't have one) so it never gets sent up to iterable (thus it never shows up in devices array)

**Comment by jmejiamu** [comment]
Yes, I tested it on a simulator. That's why I do not see it in the Iterable user's profile. Thanks that make sense.
