### ISSUE TITLE
console.log could cause performance issues, please help to add if(Iterable.savedConfig.logLevel === 1) to stop consoles

### ISSUE THREAD

**Issue by marcmoo** [Iterable/react-native-sdk#353]
Hi Iterable Support, could you help to add Iterable.savedConfig.logLevel === 1 to stop console?
```
 static initialize(apiKey, config = new IterableConfig()) {
        if (config.logLevel === 1) console.log("initialize: " + apiKey); // please add this
        Iterable.savedConfig = config;
        this.setupEventHandlers();
        const version = this.getVersionFromPackageJson();
        return RNIterableAPI.initializeWithApiKey(apiKey, config.toDict(), version);
    }

// and for each console.log please add:
 Iterable.savedConfig.logLevel === 1 && console.log(
```
or could you allow us to fork this library?
Very apprecaited!

**Comment by roninopf** [comment]
Hi @marcmoo, @alex-a-pereira, sorry for the late response, does version 1.3.2 solve this for you? You can set `logReactNativeSdkCalls` to `false` to turn off our internal `console.log` prints. I wanted to get a workable solution in (to avoid the solution hassles that @alex-a-pereira has mentioned), but I'm aware this is very basic.

I'll be closing this issue for now, but please let us know through your CSMs if you have feature suggestions for how should this evolve.
