### ISSUE TITLE
Add IterableConfig constructor object

### ISSUE THREAD

**Issue by NuroDev** [Iterable/react-native-sdk#361]
Just getting started with the SDK & I feel like it would a nice DX improvement to offer a class constructor to the `IterableConfig`, or possibly other classes too, to make it easier & cleaner to instantiate a new config instance.

## Example
```ts
// Current
const config = new IterableConfig();
config.autoPushRegistration = false;

// New
const config = new IterableConfig({
	autoPushRegistration: false,
});
```

**Comment by roninopf** [comment]
Hi @NuroDev , thanks for writing in about your experience. I'll be honest, I don't see us implementing this specific suggestion, I don't think it warrants enough of a change, however, I'm very curious to know what other suggestions (or just problems you run into) you have. Please do, and feel free, to open a ticket with your CSM, it will definitely get to us. I also have my own list of things I'd like to adjust for a better SDK usage (not just easier, but also more intuitive and predictable in behavior).

For now I'll close this specific issue, but feel free to open a new one if the occasion arises.
