### ISSUE TITLE
Flex - JWT Error Handling 

### ISSUE THREAD

**Issue by danwbyrne** [Iterable/react-native-sdk#369]
# Summary
In our mobile integration of Iterable with the Flex onboarding app we are running into a problem where JWT auth is not present at the right times for calling `updateEmail(...)` and `updateUser(...)`

This problem is inconsistent and will sometimes work as expected, but happens enough that it is a blocker for us.

A typical order of operations for us is:
1) a user gives us a verified phone number
1a) if the user is identified by firestore and we get an `email/phone` combination we fetch a `userId` from our backend and call `Iterable.setUser(...)` 
2) a user submits name + email to a form which identifies them in firestore if they aren't already identified and calls `Iterable.setUser(...)`
3) because unlike the web sdk the `authFunction` doesn't pass through an optional `userId`/`email` combination for us we use `Iterable.getUserId()` to provide the set userId to our backend. Unfortunately this `getUserId()` call can return undefined even though we only call it after `Iterable.setUserId(...)`
3) at this point we have definitely called `Iterable.setUserId(...)` and we call `Iterable.updateEmail(...)` with the email and `Iterable.updateUser(...)` with phone/name
4) *sometimes* the Iterable calls in (3) will succeed, sometimes only 1 will succeed and sometimes they will both fail
5) if they fail a new JWT token can be seen being fetched but an attempt is never made to call the failed requests with the new auth
6) Since `updateEmail(...)` and `updateUser(...)` are functions of type `() => void` we have no way to react to their failure states and retry the request.

![image](https://user-images.githubusercontent.com/9561608/172902253-80b94836-f083-4122-af3b-2e321c04d55f.png)
here you can see the `authTokenRequest` after `setUserId(...)` failed and returned an empty string (or it would have logged like the second auth request)

after the updateEmail/updateUser failures it does request a new JWT
![image](https://user-images.githubusercontent.com/9561608/172902509-97c58f37-195b-41fd-a774-b3360bdba411.png)

which is valid, but we have no way of making the request a second time since we don't know it failed.

# Possible Solutions
1) change the `authHandler` in `IterableConfig` to pass through the current `userId/email` it is trying to get permissions for to the fetch method like in the web-sdk (example from our web app)
![Screen Shot 2022-06-09 at 11 59 21 AM](https://user-images.githubusercontent.com/9561608/172903089-e11c2d5d-2fff-4957-a168-6e4d137a00c7.png)
instead of being argument-less and having to fetch the info from the Iterable instance that doesn't always return the proper credentials 
![image](https://user-images.githubusercontent.com/9561608/172903475-3bc61fd9-8abb-4d3b-b02d-0bdde7508251.png)

2) update the `updateEmail`/`setUserId`/`updateUser` functions to return a promise we can use to handle retrying like in the web app we can handle bad `updateEmail` calls easily like:
![image](https://user-images.githubusercontent.com/9561608/172904079-d787d2b1-bf1f-41ca-ae3c-01ff54835133.png)
here we are able to add retry logic to our update calls on bad responses and with a similar implementation we could add retry logic to bad JWT responses, where as right now we can't react to its failure/success
![Screen Shot 2022-06-09 at 12 06 44 PM](https://user-images.githubusercontent.com/9561608/172904427-c2178aea-1e1a-49ff-940e-b49ddb141018.png)
A similar PR has been opened for this already at https://github.com/Iterable/react-native-sdk/pull/268

3) Implement some internal handling that retries failed requests for JWT payload errors after receiving a new JWT. Not super sure what this would look like but if the other options are too much of a lift you could add a retryQueue to requests that fail for JWT reasons and try them 1 more time after the new auth is retrieved (since an `updateUser` JWT failure is already triggering `requestAuth`)

**Comment by davidtruong** [comment]
@danwbyrne: We are looking at adding a new delegate to the AuthHandler to include a failure callback so the application can attempt a new fetch of the JWT. Let me know if you have any further thoughts or suggestions.

**Comment by Ayyanchira** [comment]
Version [1.3.5]+(https://github.com/Iterable/react-native-sdk/releases/tag/1.3.5) now supports [authHandlers](https://github.com/Iterable/react-native-sdk/blob/b8aecc287e8aea8d1e2c9e701ad6f3cc77a8e166/ts/IterableConfig.ts#L73), accepting [AuthResponse](https://github.com/Iterable/react-native-sdk/blob/b8aecc287e8aea8d1e2c9e701ad6f3cc77a8e166/ts/IterableConfig.ts#L136-L140), in which token can be passed and success or failure callback will be called notifying whether or not the token was successfully registered by the SDK.
 
Additionally, methods [setEmail](https://github.com/Iterable/react-native-sdk/blob/b8aecc287e8aea8d1e2c9e701ad6f3cc77a8e166/ts/Iterable.ts#L216), [setUserID](https://github.com/Iterable/react-native-sdk/blob/b8aecc287e8aea8d1e2c9e701ad6f3cc77a8e166/ts/Iterable.ts#L269) and [updateEmail](https://github.com/Iterable/react-native-sdk/blob/b8aecc287e8aea8d1e2c9e701ad6f3cc77a8e166/ts/Iterable.ts#L539) now accepts optional authToken to avoid conditions as above.

This should resolve the issue. Feel free to open the issue if the problem persists
