### ISSUE TITLE
Messages overlay on IOS devices

### ISSUE THREAD

**Issue by vladiRozen** [Iterable/react-native-sdk#371]
Hi,
I am running iterable sdk on react native 0.63.4, and for some ios devices and not constantly I get an "overlay" of a text sourced from getMessages request. At that point in time, I don't initiate the request for getMessages. This request is only called at a later stage when my app is fully loaded.
For example, this might happen while the splash screen is still on and the app isn't fully loaded.

![IMG-20220708-WA0000](https://user-images.githubusercontent.com/75591466/177912986-f6b0f181-32c6-49ef-ac12-288decf64dd6.jpg)

Please advise.

**Comment by Ayyanchira** [comment]
Hi @vladiRozen, Thanks for reporting this.
You can use - `Iterable.inAppManager.setAutoDisplayPaused(true)` when you want to prevent inapps to be shown in certain screens or time. Make sure to turn it back to false when the app is ready to show the inapp. 
Reference: 
Hope this helps :)
