### ISSUE TITLE
Type 'IterableAPI' has no member 'setEmail'

### ISSUE THREAD

**Issue by BrianCortes** [Iterable/react-native-sdk#385]
Hi Guys I am trying to install the react native SDK in my project but I get this error, I am using an M1

![image](https://user-images.githubusercontent.com/18728297/184192879-539aca0c-39bb-46ca-a2b5-0f289fe18234.png)

**Comment by carl0shd** [comment]
This happens to me as well, I tested in a clean RN project.

**Comment by Ayyanchira** [comment]
1.3.5 has been released to mitigate this issue. Thank you for reporting this.
