### ISSUE TITLE
Function urlHandler doesn't run in Android

### ISSUE THREAD

**Issue by huds79** [Iterable/react-native-sdk#390]
I am using the function urlHandler to manage the deepLinks and the universal links when opening a push notification with a link.

Iterable code:
const config = new IterableConfig();
config.autoPushRegistration = true;
config.urlHandler = url => {
   handleOpenURL({ url });
   return true;
};
let result = false;
  try {
    result = await Iterable.initialize(ITERABLE_API_KEY, config);
  } catch (e) {
     crashlytics().recordError(e as Error, 'Iterable not Initialized');
  }

The deeplinks are working correctly for Android and iOs, I tried with "@iterable/react-native-sdk": "^1.3.6" and 1.3.3

When I open a push notification with a deeplink, It works perfectly in iOs, but when I try to test in Android, the function in urlHandler never is called.

You know if is a bug in the library, or a configuration additional is required, I modified the AndroidManifest file according to the documentation.

**Comment by Ayyanchira** [comment]
@huds79 , thank you for reaching out, 
Have you set the context in generated Android project as shown [here](https://support.iterable.com/hc/en-us/articles/360045714132-Installing-Iterable-s-React-Native-SDK-#_4-configure-your-native-android-project)?

```
//Application class in Android project
import com.iterable.iterableapi.IterableApi;

...
IterableApi.setContext(this);
```

**Comment by huds79** [comment]
@Ayyanchira thank you for your answer

Yes, I follow the instructions on the Installing Iterable's React Native SDK page, I have those lines in the MainApplication file.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/13575116/185958968-cbe89101-05b4-4f2f-9699-7e8b91c7a4c5.png">

**Comment by Ayyanchira** [comment]
Is it a custom link? By default, IterableSDK supports https links. However, if it is a custom link, it must be specified in [allowedProtocols](https://support.iterable.com/hc/en-us/articles/360045714132-Installing-Iterable-s-React-Native-SDK-#_6-initialize-the-sdk).

Also feel free to have your Iterable Admin create a support ticket so we can look at templates and get a deeper look why this is happening.

**Comment by huds79** [comment]
I am trying with deeplinks with this form:
appname://list/
The deeplinks are working when I open in a page or external app.
I tried with: `config.allowedProtocols = ['http', 'https', 'appname'];`
I tried with: `config.allowedProtocols = ['http', 'https', 'custom'];` too with the same result

**Comment by nprz** [comment]
Was a solution to this ever found? I'm currently experiencing the same issue as well. It seems the `handleUrlCalled` event is never called on Android. I see the event pass on iOS, but not on Android. The event listener for `handleUrlCalled` seems to get created, but the event is never fired when clicking the push notification.

**Comment by nicopir** [comment]
I'm having the same issue with my project, none of the URLs I'm providing in the OpenURL field is triggering anything (urlHandler, Linking.addEventListener, Linking.getInitialURL()). I've tried with different protocols: https and my own one from my app (defined in the AndroidManifest)... Everything is working well with my iOS app, I get the whole string provided in the openURL field.

Any solutions found?
Thanks

**Comment by devcsomnicg** [comment]
@huds79 @nicopir @nprz :

Could you guys try react-native-sdk version 1.3.12 and see if it is still reproducible? 

We tried on the same version and it is working fine. 

What we did is added a separate Intent filter to handle custom deep link like this: sampleopenapp://openlink/ in our manifest

<activity
            android:name=".MainActivity"
            android:screenOrientation="portrait"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            
            <intent-filter android:label="@string/app_name">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="sampleopenapp"
                    android:host="openlink"
                    android:pathPrefix="/" />
                 
            </intent-filter>
        </activity>
        
And also don't forget to add this custom link protocol when initialising IterableConfig as below as we did in our case:

const config = new IterableConfig();
config.allowedProtocols = ["https", "sampleopenapp"] // This will allow to detect custom link when you click on a push notification and open the app
