### ISSUE TITLE
was customActionHandler action changed?

### ISSUE THREAD

**Issue by nymphetamineinside** [Iterable/react-native-sdk#392]
We have 1.1.3 package installed.
It worked great until you changed push template form design.

We use `custom Action`. and if we type something in the field, for example `myCustomAction`
then we checked in the app as `action.type === 'myCustomAction'`.

It worked so for ages, but now we will have to check `action.data === 'myCustomAction'`
because type now is 'customAction'.

Is it an issue or was done intentionally? We can fix it easily but it excludes any backwards compatibility for our app.

Also it's related only to new onetime push campaigns. Our triggered campaigns continue working well with custom action, but i'm afraid of re-saving them. It could mean that the issue in the new template form.

For now, solution `[action.type, action.data].includes('myCustomAction')` looks better than others in case you fix the form and to support our triggered campaigns w/o re-saving them.

Could you please take a look at your new form?

Thanks!

**Comment by Ayyanchira** [comment]
Thanks for sharing this @nymphetamineinside. I'll have it looked by appropriate team.

**Comment by ahendricks** [comment]
Hi @nymphetamineinside, this should be resolved. Could you check if everything looks good from your end?

**Comment by nymphetamineinside** [comment]
a

> Hi @nymphetamineinside, this should be resolved. Could you check if everything looks good from your end?

Thanks a lot! Checking now

**Comment by nymphetamineinside** [comment]
@ahendricks 
Custom action works as expected now.

Thanks!
