### ISSUE TITLE
[iOS][In-App messages] - Invalid API Key

### ISSUE THREAD

**Issue by p-sebastian** [Iterable/react-native-sdk#493]
## Update

Turns out if you use the
```typescript
const token = await getYourJWT()
Iterable.setUserId(id, token)
```
it will ignore it on the native side, the JWT must be fetched on the `authHandler` on the config you pass to initialize
```typescript
config.authHandler = async () => {
     const { data } = await getYourJWT()
     return data
};
```

---
## OLD
I have the Iterable configured to Receive Push Notification, that has been working for a while, but now I am trying to set up `in-App Messages`

Looking at the xcode logs, it seems that 
```swift
private func synchronize(appIsReady: Bool) -> Pending<Bool, Error> {
        ITBInfo()
        
        return fetcher.fetch() // this fails with Optional("Invalid API Key")
       ...
}
```

Although the key is being correctly initialized in the React Native TS code, with `JWT`, it appears that the native side isn't getting the API key.

I tried adding this to the `application` in the `AppDelegate` which is a non-JWT enabled key, if I pass a JWT enabled key, it fails from the beginning.
```obj-c

  IterableConfig *config = [[IterableConfig alloc] init];
  [IterableAPI initializeWithApiKey:@"xxxxxxxxxx-non-jwt-key" launchOptions:launchOptions config:config];
```
Which makes the `in-App` message display once on launch, but with this error on all events of the in-app message, after that any time I send a in-app message it just fails.
```
Invalid API Key, got response {"msg":"JWT Authorization header is not set}
```

----
* Shouldn't this already be handled from the TS code in react native, or does it require a copy of the logic in Obj-C?
* Push notification are already working both in background/foreground and app closed
* events do work

----
```
* "@iterable/react-native-sdk": "1.3.13"
* "react-native": "0.70.3",
```

**Comment by Ayyanchira** [comment]
Thanks for detailed review and solution (cherry) on top :)
