### ISSUE TITLE
Bug: Android background push notification actions don't wake up RN SDK if app closed

### ISSUE THREAD

**Issue by jehartzog** [Iterable/react-native-sdk#81]
### Reproduction

1. Using Android RN app, add a `customActionHandler` to this lib.
1. Using Iterable Web UI, create a push template with a push action button with `Open app` option **NOT** selected.
1. Start the app, then force close it using Android swipe gesture.
1. Using Iterable Web UI, send push to device, press on the Notification Action on device.

### Expected

1. Notification will dismiss
1. App will wake in background, execute action. No visible UI will be shown. Action is completed successfully.

### Actual

1. Notification dismisses
1. Nothing else

### Environment:

1. `@iterable/react-native-sdk` `1.0.12` (forked by #79)
1. `react-native` `0.63.3`
1. `Android OS` `10`

### Suspected cause

This one is related to the #76 we worked through, except the solution isn't as straightforward. I couldn't figure out a proper PR to fix this, as it relates to behavior between `react-native-sdk` and `iterable-android-sdk`.

The problem starts [here](https://github.com/Iterable/iterable-android-sdk/blob/85edd3322a442b733b5bc2a19a3f1b1aa2c57591/iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java#L86) when we are thinking about the case where `openApp` is `false` AND the Android app is closed/terminated. When this occurs, this `react-native-sdk` never receives the call [here](https://github.com/Iterable/react-native-sdk/blob/459201fa5da4d3022c69a9e7ad528d38ea63e581/android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java#L383). I suspect this may be related to [this comment](https://github.com/Iterable/react-native-sdk/issues/80#issuecomment-703904899) which talks about the different times of initializing this lib vs `iterable-android-sdk`.

I've found that the `iterable-android-sdk` has no knowledge that there is 'linked' `iterable-react-sdk` that actually cares about these calls, and so no effort is made to 'wake up' the RN side in order to pass along the event.

### Our Workaround

Given time constraints I couldn't figure out the 'right' way to fix this in a PR'able solution, but was able to hack into `iterable-android-sdk` a call directly to an Android service we created which spins up our app in a `headlessJS` so that we're able to take the action in the background. You can see the important code changes [here](https://github.com/Iterable/iterable-android-sdk/compare/master...ourfabriq:fork/3.2.4-android-focus#diff-65d6554bbd3945d7fc1e998a290f6295), but ignore all the `node_modules` spam.

The way better place to make this change would be [here](https://github.com/Iterable/react-native-sdk/blob/459201fa5da4d3022c69a9e7ad528d38ea63e581/android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java#L383), as it could be PR'ed into to make this lib work out of the box for others. But as I said above, I found that function doesn't get called when the app is closed, which is why I had to go back all the way to `iterable-android-sdk`.

This was the last major issue we found so far when creating a full suite of notification actions using this lib, so with this rough fix in place we're at a good place for final testing before releasing to production.

**Comment by vbabenkoru** [comment]
@jehartzog Thank you for the report! This should be fixed with the new release, 1.0.19.
