### ISSUE TITLE
Bug: doesn't build on ios lower than 14

### ISSUE THREAD

**Issue by fernandatoledo** [Iterable/react-native-sdk#82]
When building the iOS app the compilation fails with the following error: Type 'UIUserInterfaceIdiom' has no member 'mac'

the mac value was added in iOS 14, as specified in the documentation: https://developer.apple.com/documentation/uikit/uiuserinterfaceidiom/mac

**Comment by roninopf** [comment]
Hi @fernandatoledo, thanks for writing in! We just released 1.0.15; can you try that and see if that fixes this? We know that it's been fixed on the native side, and the 1.0.15 release points to the latest iOS SDK now (2 days ago as of writing).
