### ISSUE TITLE
Bug: Android InApp messages rendered incorrectly (too small, stuck at top of screen)

### ISSUE THREAD

**Issue by jehartzog** [Iterable/react-native-sdk#93]
## Description

We're seeing on a range of Android devices that the InApp messages are being rendered incorrectly. We've tried different `Display type` settings, including `Center`, `Full`, and `Bottom`, but the webview often gets rendered at the very top of the screen in way too small of a scale.

I've seen a few cases where it seemed to render correctly, so this issue may be conditional. But we're definitely seeing the majority of the tests being incorrectly rendered.

### Expected (iOS Sim)

![image](https://user-images.githubusercontent.com/14143246/99599324-5c0cdc00-29b8-11eb-88f0-7b512df9febd.png)

### Actual (Android device)

![image](https://user-images.githubusercontent.com/14143246/99597548-64174c80-29b5-11eb-8d18-baf6f32730b4.png)

## Environment

- `react-native`: v63.3
- Android OS: 10 & 11
- `@iterable/react-native-sdk`: v1.0.18 & v1.0.12

## Troubleshooting

I looked through [IterableInAppFragmentHTMLNotification](https://github.com/Iterable/iterable-android-sdk/blob/bca3bdc687f3102794131dec9adbb97cca97ec3c/iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java) but couldn't locate any obvious reason this was occurring.

Could possibly be caused by [this](https://github.com/Iterable/iterable-android-sdk/blob/8169115832277912fe62fe8ebb7bd4ee39503fe6/iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java#L38) but I didn't validate that guess.

**Comment by vbabenkoru** [comment]
@jehartzog Thank you for the report! This is very likely content-specific, and for that I think the best channel would be to contact our Technical Support; they'll escalate to Engineering so we can look and try to reproduce this with a specific campaign. Thanks!

**Comment by jehartzog** [comment]
@vbabenkoru Thank you for response! I'm happy to go through Technical Support channel, and will do so immediately. I have my doubts though this is content-specific, I have created a minimal content example which reproduces this for us:

```
<html>
  <head>
    <title></title>
  </head>
  <body>
    <p><span style="font-size:72px;"><a target="_blank" href="iterable://dismiss">CONSUME ME</a></span>
    </p>
  </body>
</html>
```
Result:

![image](https://user-images.githubusercontent.com/14143246/99736468-a6a75a80-2a83-11eb-801b-2a3064564bbc.png)

That being said, I will continue w/ Technical Support path. Thank you again.

**Comment by jehartzog** [comment]
Thanks again for the assistance here, the issue was content related. They aren't necessary for iOS but break Android pretty badly if they are excluded:

- To allow vertical alignment/centering to work, `<!DOCTYPE html>` is needed at the top.
- The fix the scaling issue, `<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">` must be included.

These are not included in the default template when you choose to `create new WYSIWYG template`, so you must remember to add them yourself.

Here is a [link to the Iterable doc example](https://support.iterable.com/hc/en-us/articles/360035171132-Image-Carousels-in-In-App-Messages-) that was used to figure this out.
