### ISSUE TITLE
Thread 6: EXC_BAD_ACCESS (code=1, address=0x1)

### ISSUE THREAD

**Issue by yum650350** [Iterable/react-native-sdk#98]
iOS build success but crash when `Iterable.initialize` is called

![Screen Shot 2020-12-14 at 10 38 11 AM](https://user-images.githubusercontent.com/48589760/102034260-88214e80-3df8-11eb-8b30-09b30f400549.png)

```ts
  const Config = new IterableConfig();

  Config.urlHandler = (url: string, _context: IterableActionContext) => {
    pageNavigation(url);

    return true;
  };

  Iterable.initialize(config.ITERABLE_APP_ID, Config);
```

### Environment
```
// package.json
"@iterable/react-native-sdk": "1.0.18",
"react-native": "0.60.6",

// Podfile
platform :ios, '11.0'
```

**Comment by roninopf** [comment]
Hi @yum650350, just for more clarification, you only set the `urlHandler`, but then it's crashing on the `authDelegate`?

**Comment by yum650350** [comment]
@roninopf Yes, we only set the `urlHandler`, but this crash never present after we upgraded React Native to 0.63.3.

Not sure if this is due to we frequently switch between react-native 0.60.6 and 0.63.3 during the upgrading work phase. 

Anyway, it isn't an issue for us right now, so closing this issue as well.

Thanks for your attention.
